Parameterized latency distribution through FMA
bsg-external/HardFloat pull request #8
Opened 2021-07-17 08:11 UTC by mysoreanoop

Goes with the changes in bp_be_pipe_fma.v

2021-07-17 09:23 UTC, dpetrisko commented
see comments on https://github.com/black-parrot/black-parrot/pull/899

2021-07-17 09:24 UTC, dpetrisko commented on source/mulAddRecFN.v
> +        parameter integer latencyDstr[0:1] = {0,0},
Comment with experimentally determined values

2021-07-17 09:24 UTC, dpetrisko commented on source/mulAddRecFN.v
>      mulAddRecFNToRaw#(
Add diagram of where the retiming is happening

2021-07-17 09:25 UTC, dpetrisko requested changes
Cool!

2021-07-17 12:36 UTC, mysoreanoop commented on source/mulAddRecFN.v
>      mulAddRecFNToRaw#(
Roger that

2021-07-17 21:01 UTC, taylor-bsg requested changes

2021-07-17 21:01 UTC, taylor-bsg commented on source/mulAddRecFN.v
> + * latencyDstr is used to distribute the latency manually
A more standard terminology would be "insert pipelining registers"

2021-07-17 21:01 UTC, taylor-bsg commented on source/mulAddRecFN.v
> + *  - Default '{0,0}
No pipelining (default): '{0,0}
64-bit, Zynq 7020 @ 50 MHz:

2021-07-17 21:01 UTC, taylor-bsg commented on source/mulAddRecFN.v
> + *      |   DSP
Integer MulAdd (uses DSP on Zynq 7020)

2021-07-17 21:01 UTC, taylor-bsg commented on source/mulAddRecFN.v
> +        parameter int latencyDstr[0:1] = '{0,0},
Pipeline

2021-07-17 21:01 UTC, taylor-bsg commented on source/mulAddRecFN.v
> +    bsg_dff_chain#(sigWidth*4, latencyDstr[0])
Code going top to bottom should follow the data path from left to right.

2021-07-18 20:45 UTC, taylor-bsg commented on source/mulAddRecFN.v
> +    wire [sigWidth*2:0] mulAddResult = mulAddA_Z * mulAddB_Z + mulAddC_Z;
let's pull this out into a basejump_stll bsg_mul_add module, where the A input, B input and output sizes are parameters; and where we pass in as a parameter the # of pipeline stages. The /hard implementation can design where to place the flops based on the target.

2021-07-22 03:20 UTC, taylor-bsg commented on source/mulAddRecFN.v
> +    wire [5:0] intermed_compactState_Z;
related signals should be place on same line; e.g.

wire [5:0] intermed_compactState, intermed_compactState_Z;

2021-07-22 03:22 UTC, taylor-bsg commented on source/mulAddRecFN.v
> + * TODO: remove after bsg_mul_add.v implementation
fix comment

2021-07-22 03:22 UTC, taylor-bsg approved these changes
Good to go after you fix the small changes I suggested.

2021-07-24 17:00 UTC, dpetrisko commented
>Good to go after you fix the small changes I suggested.

I would rather see the pre-mul and pre-round retime registers in this module than externally: https://github.com/black-parrot/black-parrot/pull/899/files

2021-07-27 01:45 UTC, dpetrisko commented
>I would rather see the pre-mul and pre-round retime registers in this module than externally: https://github.com/black-parrot/black-parrot/pull/899/files

Hi @mysoreanoop, discussed offline with @taylor-bsg. We would like mulAddRecFN to have a two-entry latency parameter -- one for the mulAddRecFNToRaw the way it's currently set up, and one for between mulAddRecFNToRaw and roundRawFNToRecFN. This will allow users of mulAddRecFN to benefit from the extra round retiming, although it will not change the blackparrot implementation which will still need to deal with latency management.

2021-07-29 17:34 UTC, mysoreanoop commented
Updated

2021-07-29 18:45 UTC, mysoreanoop commented
If the parameters of `bsg_mul_add_unsigned` change, we should make sure to update this file. Or shall we just instantiate it in named-ports style?

2021-07-29 23:24 UTC, taylor-bsg commented
@mysoreanoop BSG style is to use named ports in code we write. But can't guarantee that others will do so.

2021-07-29 23:25 UTC, taylor-bsg commented
@tommydcjung Anoop is adding support for passing in pipeline parameters for the FMA; this allows us to get pipelining to work with Zynq for BlackParrot. Unclear if it necessary or useful for manycore, but If they are set to 0, then it should have the same behavior as before. But heas

2021-07-29 23:25 UTC, taylor-bsg commented
@dpetrisko ready to merge?

2021-07-29 23:38 UTC, merged

2021-08-06 05:46 UTC, taylor-bsg commented
@mysoreanoop congrats on your accepted pull request! Nice work.